### ISSUE TITLE
setup help: requesting explicit list of dependencies to install

### ISSUE THREAD

**Issue by yodurr** [voodooattack/nexusjs#11]
On Ubuntu 16 it's tricky to figure out which dependencies are needed.  Can we put a list together in the docs?

I know of these: libicu-dev

**open issue**: cmake script can't find curl even though libcurl3 is installed

**open issue**: apt install boost-all-dev on Ubuntu 16 is installing a too old version of boost (1.58).  Are you getting boost 1.62 from source? 

CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.
  Boost version: 1.58.0
  Boost include path: /usr/include
  Detected version of Boost is too old.  Requested version was 1.62 (or
  newer).

**Comment by yodurr** [comment]
also noticed it's pulling the head of webkit master as it can't find the sha.
Unable to checkout '5a21764de110a9482159e7e7cc131bf20c49e7c6' in submodule path 'vendor/webkit'

**Comment by voodooattack** [comment]
@yodurr That'd be the infamous #5, still wrapping my head around it. `git reset --hard` in the `vendor/webkit` subdirectory fixes it temporarily though.

Unfortunately, I'm not an expert with git.

**Comment by voodooattack** [comment]
The list of deps boils down to this:
```
apt-get install build-essential cmake libboost-all-dev curl libcurl4-openssl-dev g++ \
  libicu-dev ruby perl xxd libicu60
```
 I just finished the Docker integration, which boils down to these for a successful build. Note that perl and ruby are only required for WebKit to build.
