### ISSUE TITLE
Please change the license

### ISSUE THREAD

**Issue by mchiasson** [voodooattack/nexusjs#13]
I'm no legal expert, but it was explained to me that GPL means that even derivative work that doesn't even change the original code would be contaminated by GPL license and become open source no matter what.

**Comment by mchiasson** [comment]
BSD, MIT and Apache are great choices. If you absolutely want GPL, you should consider LGPL like JavaScriptCore.  LGPL is pretty much the same than GPL with an exemption on derivative work. Again, I am no legal expert, but I am pretty sure that external native modules would count as derivative work

**Comment by voodooattack** [comment]
Would that mean that mixing GPL-licensed native addons with incompatible ones in a Node.js application is a license violation?

It’s a right mess in any case, but I’d be willing to explicitly add an exception to the license if someone can write it up.
