### ISSUE TITLE
Feature Support: ES2015 import and export

### ISSUE THREAD

**Issue by jtenner** [voodooattack/nexusjs#3]
I figured we could leave this as an open issue to discuss how this could be done.  It's my understanding that webkit does not support this yet.

Any thoughts?

**Comment by voodooattack** [comment]
It could probably be done by transpiling the sources right before execution. I'll look into it.

**Comment by jtenner** [comment]
Should we wait for webkit to support the syntax natively?  That might be the better option.

**Comment by voodooattack** [comment]
We just might, but I want to support this either way.

**Comment by voodooattack** [comment]
ES6 Support has just landed in the last commit. I'm closing this now. :+1:
