### ISSUE TITLE
submodule problem

### ISSUE THREAD

**Issue by mingfang** [voodooattack/nexusjs#5]
Submodule 'vendor/beast' (https://github.com/boostorg/beast.git) registered for path 'vendor/beast'
Submodule 'vendor/webkit' (https://github.com/WebKit/webkit.git) registered for path 'vendor/webkit'
Cloning into 'vendor/beast'...
fatal: reference is not a tree: 9dc9ca13b9c08c1597d05bcf6c19be357e426041
Cloning into 'vendor/webkit'...
fatal: reference is not a tree: c7e2ef8fc3620c4c90f2b3262c41a34d1812fc85
Unable to checkout '9dc9ca13b9c08c1597d05bcf6c19be357e426041' in submodule path 'vendor/beast'
Unable to checkout 'c7e2ef8fc3620c4c90f2b3262c41a34d1812fc85' in submodule path 'vendor/webkit'

**Comment by voodooattack** [comment]
I’ll look into this once I get back to my development machine. Thanks for the report!

**Comment by voodooattack** [comment]
@mingfang Just tested on a fresh setup and it works. Please let me know if the issue persists.

**Comment by mingfang** [comment]
it looks like ```git submodule update --init --recursive --depth 1``` doesn't work but ```git submodule update --init --recursive``` works

**Comment by voodooattack** [comment]
@mingfang Thanks for reporting this. I’ll update the readme accordingly.

**Comment by WebReflection** [comment]
not sure 'cause I haven't tried the second one ... but ... 

```
git submodule update --init --recursive
error: Server does not allow request for unadvertised object b5748db0859e0ff03b29f30e345a511deea8dde8
Fetched in submodule path 'vendor/webkit', but it did not contain b5748db0859e0ff03b29f30e345a511deea8dde8. Direct fetching of that commit failed.

```

**Comment by voodooattack** [comment]
@WebReflection Can you try this: `git submodule sync` and see if it works or not?

**Comment by WebReflection** [comment]
> Can you try this: git submodule sync and see if it works or not?

just done that, it doesn't work.

**Comment by WebReflection** [comment]
out of curiosity @voodooattack, when are you planning to go back to this project?

**Comment by voodooattack** [comment]
When I’m back from vacation. Sorry for not mentioning this earlier. :)

Sent from my iPhone

On Jan 9, 2018, at 1:18 PM, Andrea Giammarchi <notifications@github.com<mailto:notifications@github.com>> wrote:


out of curiosity @voodooattack<https://github.com/voodooattack>, when are you planning to go back to this project?

**Comment by pytlesk4** [comment]
Running into the same issues. Any solutions to this?

**Comment by voodooattack** [comment]
Fixed by using SVN to checkout WebKit directly during build.
