### ISSUE TITLE
Anyway to use this with Node.js?

### ISSUE THREAD

**Issue by DakshMiglani** [voodooattack/nexusjs#7]

**Comment by derhuerst** [comment]
see https://github.com/voodooattack/nexusjs/issues/6#issuecomment-350546528

**Comment by voodooattack** [comment]
I’m not sure I understand the question. 

Nexus.js is a stand-alone JavaScript runtime environment, and not a Node.js framework/library.

**Comment by DakshMiglani** [comment]
I get that but just like chakracore, is there a way to use multi-threaded workflow with node.js or do you have any plans to work this out with node.js?

**Comment by voodooattack** [comment]
If you’re asking whether or not I’m planning to implement a compatibility layer with Node.js, then the answer is no. Nexus is a separate project with a different focus from Node. 

I see no reason why people won’t implement their own in the future though. Once there’s a package manager and an ecosystem/platform to publish modules.

**Comment by DakshMiglani** [comment]
Alrighty!
